BookEditorBundle\Entity\PressArticle:
    type: entity
    table: null
    repositoryClass: BookEditorBundle\Repository\PressArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        imageUrl:
            type: string
            length: 255p
        uploaded:
            type: datetime
            nullable: true
    manyToOne:
        book:
            targetEntity: Book
            inversedBy: press_articles
            joinColumn:
                name: book_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
