BookEditorBundle\Entity\PressArticle:
    type: entity
    table: null
    repositoryClass: BookEditorBundle\Repository\PressArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        imageUrl:
            type: string
            length: 255
    lifecycleCallbacks: {  }
