book_editor:
    resource: "@BookEditorBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

login:
    path: /login
    defaults:
        _controller: BookEditorBundle:Security:login

logout:
    path: /logout