book_index:
    path:     /
    defaults: { _controller: "BookEditorBundle:Book:index" }
    methods:  GET

book_ourBooks:
    path:     /nos-livres
    defaults: { _controller: "BookEditorBundle:Book:ourBooks" }
    methods:  GET

book_showToPublic:
    path:     /livre/{slug}
    defaults: { _controller: "BookEditorBundle:Book:showToPublic" }
    methods:  GET

book_aboutUs:
    path:     /etre-edite
    defaults: { _controller: "BookEditorBundle:Book:aboutUs" }
    methods:  GET

book_legalNotice:
    path:     /mentions-legales
    defaults: { _controller: "BookEditorBundle:Book:legalNotice" }
    methods:  GET
