book_index:
    path:     /
    defaults: { _controller: "BookEditorBundle:Book:index" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "BookEditorBundle:Book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "BookEditorBundle:Book:new" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "BookEditorBundle:Book:edit" }
    methods:  [GET, POST]

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "BookEditorBundle:Book:delete" }
    methods:  DELETE

book_aboutUs:
    path:     /etre-edite
    defaults: { _controller: "BookEditorBundle:Book:aboutUs" }
    methods:  GET